# Site wide configuration
source                   : .tmp/src
destination              : .tmp/dist

title                    : "Odayaka cho thuê xe Honda Phú Quốc Island"
description              : "Cung cấp dịch vụ cho thuê xe Honda Phú Quốc, giá thành rẻ, xe mới, nhận xe tại sân bay Phú Quốc. Có nhà nghỉ tại Bãi Thơm, Hàm Ninh, An Thới liên hệ 0899150055 để được tư vấn."
logo                     : "/assets/images/android-chrome-384x384.png"
teaser                   : "/assets/images/default-teaser.png"
locale                   : "en_US"
words_per_minute         : 200

repository               : "dchcm/odayaka"
url                      : "https://thuexehonda.com"

social:
  name                   : "Odayaka"
  links:
    - "https://twitter.com/odayakada"
    - "https://www.facebook.com/OdayakaPhuQuoc"
    - "https://www.instagram.com/odayakada/"
    - "https://github.com/odayakada"
    - "https://plus.google.com/u/0/+OdayakaHondaPhúQuốc/posts"

google_site_verification : "jCWEhb2Qg9YXw-9hhKgRFKohyKZhW35fCkAAyBkk1us"
bing_site_verification   : "5978D3B10A5096B9050799E8A45A2003"
alexa_site_verification  : "MãxácnhậnAlexa"
yandex_site_verification : "IDHERE-ĐãxácnhậnthôngquaEmailYandex"

google_ad-client         : "ca-pub-9055751449136582"
google_ad-slot           : "2288106514"
google_analytics         : "UA-117154167-1"

feed:
  path                  : "https://thuexehonda.com/atom.xml"

favicon_version         : "5A54z5oklP"

pingback_url            : "https://webmention.io/thuexehonda.com/xmlrpc"
webmention_url          : "https://webmention.io/thuexehonda.com/webmention"
micropub_url            : "http://sitewriter.net/thuexehonda.com/micropub"

# Site owner
author:
  name                   : "Odayaka"
  uri                    : &uri "https://thuexehonda.com/about/"
  url                    : *uri
  bio                    : "Chuyên về lĩnh vực quảng cáo và sản phẩm năng lượng tái tạo."
  picture                : "/assets/images/michael-rose-glitched.jpg"
  twitter                : "https://twitter.com/odayakada"
  facebook               : "https://www.facebook.com/OdayakaPhuQuoc"
  instagram              : "tel:+840899150055"
  tumblr                 : "http://thuexehonda.com/"
  github                 : "https://github.com/odayakada"
  messenger              : "http://m.me/OdayakaPhuQuoc"
  phonenumber            : "tel:+84-089-915-0055"
  zalo                   : "https://zalo.me/odayakapqc"
  google_plus            : "https://plus.google.com/+OdayakaHondaPhúQuốc/posts"

twitter:
  username               : "odayakada"

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch                 : "master"

# reCAPTCHA keys
reCaptcha:
  siteKey: "6LdtzVYUAAAAAKb2JK_IAdG7A2iX2Xe4cDG9VBDV"
  secret: "6LdtzVYUAAAAAFqWu88U_TbsXue0QaWp7zECwx9J"

# Jekyll configuration
permalink                : /:categories/:title/
lsi                      : false
future                   : false
show_drafts              : false
markdown                 : kramdown
kramdown:
  toc_levels             : 1..3
  input                  : GFM
  hard_wrap              : false
  auto_ids               : true
  entity_output          : as_char
  smart_quotes           : lsquo,rsquo,ldquo,rdquo
  enable_coderay         : false
highlighter              : rouge
strict_front_matter      : true
keep_files:
  - .git
include:
  - .htaccess
  - _pages
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Capfile
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-typogrify
  - jekyll/figure
  - jekyll-algolia
  - jekyll/tagging
  - jekyll-tagging-related_posts

# Collections
collections:
  faqs:
    output    : true
    permalink : /:collection/:path/
    title     : Câu hỏi thường gặp
  work:
    output    : true
    permalink : /:collection/:path/
    title     : Sản phẩm Dịch vụ Odayaka Honda Phú Quốc
  components:
    output    : false
  colors:
    output    : false

# Front Matter Defaults
defaults:
  # Blog Articles
  - scope:
      path: _posts/articles
      type: posts
    values:
      layout: post
      category: articles
      read_time: true
      support: true
      image:
        cover: true
      breadcrumbs:
        - label: "Bài viết của Odayaka"
          url: /articles/
  # From Phu Quoc
  - scope:
      path: _posts/phuquoc-city
      type: posts
    values:
      layout: post
      category: phuquoc-city
      read_time: true
      comments: true
      support: true
      breadcrumbs:
        - label: "Từ Phú Quốc"
          url: /phuquoc-city/
      image:
        cover: true
  # RentAMotorbike
  - scope:
      path: _posts/thuexe
      type: posts
    values:
      layout: post
      category: thuexe
      breadcrumbs:
        - label: "Thuê Xe Honda Phú Quốc"
          url: /thuexe/
      work: "Thuê xe Honda Phú Quốc"
      seo:
        type: "CreativeWork"
  # Procreate Paintings
  - scope:
      path: _posts/procreate
      type: posts
    values:
      layout: post
      category: procreate-paintings
      breadcrumbs:
        - label: "Cho thuê Homestay"
          url: /procreate-paintings/
      work: "Illustration"
      seo:
        type: "CreativeWork"
  # TIL
  - scope:
      path: _posts/til
      type: posts
    values:
      layout: post
      category: til
      read_time: true
      comments: true
      support: true
      breadcrumbs:
        - label: "Hôm nay tôi đã học được gì?"
          url: /til/
  # Sản phẩm Năng lượng mặt trời
  - scope:
      path: _posts/nangluongmattroi
      type: posts
    values:
      layout: post
      category: nangluongmattroi
      breadcrumbs:
        - label: "Sản phẩm năng lượng mặt trời"
          url: /nangluongmattroi/
      work: "Sản phẩm năng lượng tái tạo"
      seo:
        type: "CreativeWork"
  # Work (posts and collection)
  - scope:
      path: _posts/work
      type: posts
    values:
      layout: post
      category: work
      breadcrumbs:
        - label: "Sản phẩm, Dịch vụ Odayaka Honda Phú Quốc"
          url: /work/
      seo:
        type: "CreativeWork"
  - scope:
      path: _work
      type: work
    values:
      layout: work
      category: work
      breadcrumbs:
        - label: "Sản phẩm, Dịch vụ Odayaka Honda Phú Quốc"
          url: /work/
      seo:
        type: "CreativeWork"
  # FAQs
  - scope:
      path: _faqs
      type: faqs
    values:
      layout: page
      read_time: true
      breadcrumbs:
        - label: "Câu hỏi thường gặp"
          url: /faqs/
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  debug: false
  per_page: 15
  permalink: "/page/:num/"
  title: ":title - Page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    enabled: true
    slugify:
      mode: raw
      cased: true
    layouts:
      - "autopage_tags.html"
    title: ":tag" # :tag is replaced by the tag name
    permalink: "/tag/:tag"

# Plugin: Jekyll Algolia
algolia:
  application_id: UPW0YSDBU4
  index_name: odayaka
  search_only_api_key: 5f43d0035ead958f40682b78717b941b
  nodes_to_index: "p"
  files_to_exclude:
    - index.html
    - index.md
    - excluded-file.html
    - _pages/404.md
    - _pages/articles.md
    - _pages/faqs.md
    - _pages/phuquoc-city.md
    - _pages/portraits.md
    - _pages/sitemap.md
    - _pages/tag.md
    - _pages/til.md
    - _pages/work.md
